on:
  rss:
    url: 
      - https://adbackstage.libsyn.com/rss # Android Developers Backstage
      - https://appsgamesinsights.libsyn.com/rss # Apps, Games, & Insights Podcast
      - http://nowinandroid.googledevelopers.libsynpro.com/rss # Now in Android
jobs:
  telegram:
    name: Send a telegram message
    runs-on: ubuntu-latest
    steps: 
      - name: Send a telegram message
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            *${{on.rss.outputs.title}}*

            *${{on.rss.outputs.content}}*

            *${{on.rss.outputs.link}}*
          format: html
          disable_web_page_preview: false
