on:
  rss:
    url: 
      - http://androidbackstage.blogspot.com/feeds/posts/default # Android Developers Backstage
      - https://medium.com/feed/androiddevelopers # Android Developers on Medium
      - https://blog.jetbrains.com/kotlin/feed/ # Official Kotlin Blog
jobs:
  telegram:
    name: Send a telegram message
    runs-on: ubuntu-latest
    steps: 
      - name: Send a telegram message
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            *${{on.rss.outputs.title}}*

            *${{on.rss.outputs.link}}*

            *${{on.rss.outputs.content}}*
          format: markdown
          disable_web_page_preview: false
